### PR TITLE
called out Towely

### PR DESCRIPTION
**Pull request by ia-dbuckholz**

### CODE REVIEW

**Comment by ia-dbuckholz** [comment]
I challenge you to merge this, squash my comment out of it without losing the file change, and open a new pull request to dutchb/ABC_Branch

**Comment by michmalibu** [comment]
"squash my comment out of it" -- did you mean "squash my commit out of it?"

**Comment by michmalibu** [comment]
Merging Dutch's change on someOtherFile

**Comment by ia-dbuckholz** [comment]
so if I use `git log` on your branch I no longer see my commit, but if I open the file I still see the change

**Pull request merged**
